Development page added
codeiiest-dev/codeiiest-web pull request #16
Opened 2020-12-06 06:48 UTC by berakrishnendu36

2020-12-06 07:01 UTC, raydwaipayan requested changes
Please put package-lock.json into .gitignore.

Rest some changes and we are good to go.

2020-12-06 07:14 UTC, berakrishnendu36 commented on pages/chapters/development.vue
> +        <vue-particles
okayy.. 😅

2021-03-27 17:29 UTC, raydwaipayan commented
@raydwaipayan resolve merge conflict

2021-03-27 18:26 UTC, raydwaipayan commented
Added via commit f4156f5f49c76b1d599c975fc725efc78ffaad82

2021-03-27 18:26 UTC, closed without merging